# Nome do workflow

name: CI-Robot

# Comantos de configuração. 
on:
  # sempre que tiver um envio para origin ele vai executar estes comandos
    # Gatilhos de execuções, podendo agendar apra um determinado horário
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Abilitar workflow manualmente
  workflow_dispatch:

# Tarefas do workflow
jobs:
  # Onde quero executar o fluxo de trabalho
  build:
    # Executar em um windows-latest, ubuntu-latest
    runs-on: ubuntu-latest
    
    # Qual versão do node vai ser utilizada
    strategy:
      matrix:
        node-version: [12.x]
    
          uses: joonvena/robotframework-reporter-action@v0.1
        
          #Enviar para o git hub pages
        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{SECRETS.GITHUB_TOKEN}}
            BRANCH: gh-pages
            FOLDER: parodify/results/*.*
